### ISSUE TITLE
Fatal error: Call to a member function get() on null in /Application/view/application/image/upload.phtml on line 5

### ISSUE THREAD

**Issue by ghost** [olegkrivtsov/using-zend-framework-3-book#2] opened 2016-09-12 05:07 UTC
Followed your tutorial and got this error when I tried to go to the upload page. The file was originally upload.html but that produced another error that was fixed when I changed it to .phtml.

Please help

Thanks

**Comment by olegkrivtsov** [comment] 2016-09-12 05:20
Hi @Farsideman 

> The file was originally upload.html

This is a typo. It should be `upload.phtml`. I'll fix this.

> Fatal error: Call to a member function get() on null in /Application/view/application/image/upload.phtml on line 5 #2

This error is probably because you have empty '$form' variable (or do not pass the form from controller to view template. Could you please paste the code of your controller's action and view template?

**Comment by olegkrivtsov** [comment] 2016-09-12 13:38
> This is a typo. It should be upload.phtml. I'll fix this.

Fixed.

**Comment by ghost** [comment] 2016-09-12 14:50
The uploadAction() method:

```
// This action shows the image upload form. This page allows to upload
// a single file.
public function uploadAction()
{
    // Create the form model.
    $form = new ImageForm();

    // Check if user has submitted the form.
    if($this->getRequest()->isPost()) {

        // Make certain to merge the files info!
        $request = $this->getRequest();
        $data = array_merge_recursive(
            $request->getPost()->toArray(),
            $request->getFiles()->toArray()
        );

        // Pass data to form.
        $form->setData($data);

        // Validate form.
        if($form->isValid()) {

            // Move uploaded file to its destination directory.
            $data = $form->getData();

            // Redirect the user to "Image Gallery" page.
            return $this->redirect()->toRoute('images');
        }

        // Render the page.
        return new ViewModel([
            'form' => $form
        ]);
    }
}
```

View template upload.phtml:

```
<?php

$form = $this->form;
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Upload a New Image</h1>

<p>
  Please fill out the following form and press the <i>Upload</i> button.
</p>

<div class="row">
  <div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
      <?= $this->formLabel($form->get('file')); ?>
      <?= $this->formElement($form->get('file')); ?>
      <?= $this->formElementErrors($form->get('file')); ?>
    </div>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
  </div>
</div>
```

**Comment by olegkrivtsov** [comment] 2016-09-12 15:40
It seems that your `uploadAction()` method is incorrect - it returns the `ViewModel` only when the method is `POST`. If method is `GET`, it returns nothing. In the book, this method seems to be correct. Probably, you copied the code incorrectly. 

Does this fix your problem?

**Comment by ghost** [comment] 2016-09-12 17:05
Thank you it works now.

**Comment by olegkrivtsov** [comment] 2016-09-12 17:24
Closing.

**Closed as completed by olegkrivtsov** 2016-09-12 17:24 UTC

**Comment by inesmierpelaez** [comment] 2017-09-07 16:01
I am having a similar error, and I think I copied the code correctly. 
In the controller I have : 

public function makeCall()
    {
    	$form= new Click2CallForm();

    	// Check whether this post is a POST request.
        if ($this->getRequest()->isPost()) {
            
            // Get POST data.
            $data = $this->params()->fromCall();
            
            // Fill form with data.
            $form->setData($data);
            if ($form->isValid()) {
                                
                // Get validated form data.
                $data = $form->getData();
                
                // Use post manager service to add new call to the database             
                $this->callManager->makeNewCall($data);
                
                // Redirect the user to "index" page.
                return $this->redirect()->toRoute('application');
            }
        } //..//
And in my form: 

 public function __construct()
    {
        // Define form name
        parent::__construct('call-form');
        if($this->getRequest()->isPost()) 
     
        // Set POST method for this form
        $this->setAttribute('method', 'post');
                
        $this->addElements();
        $this->addInputFilter();         
    } //...//

**Comment by aburcheri** [comment] 2018-06-17 13:06
Have an error when I try to display a form:
` Uncaught Error: Call to a member function prepare() on null`
But when I dump my passed form in the view I see
`object(User\Form\LoginForm)#2040 (29) {...`
What may be the cause ?
